name: Deploy Frontend Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      # - name: Deploy Application
      #   run: |
      #     pm2 stop nextjs-example || true
      #     pm2 delete nextjs-example || true
      #     pm2 start npm --name nextjs-app -- run start -- -p 5000
