name: Deploy Frontend Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js App
        run: yarn build
